# Camera-specific calibration and video stream settings for the "explore_hd" model.
/**:
  ros__parameters:
    # Video stream settings
    video:
      product_name: 'exploreHD'
      width: 640
      height: 360
      framerate: 15
      format: 'MJPG'

    # Camera calibration
    camera:
      # explore air
      intrinsics:
        fx: 317.240966
        fy: 317.035766
        cx: 272.986072
        cy: 224.098703
      # distortion: [-0.319352, 0.077184, -0.001019, -0.000084, 0.000000]
      distortion: [0.0, 0.0, 0.0, 0.0, 0.0]
      fisheye: False
      undistort_crop: False