# Camera-specific calibration and video stream settings for the "usbpcb" model.
/**:
  ros__parameters:
    # Video stream settings
    video:
      product_name: 'H264'
      width: 640
      height: 360
      framerate: 15
      format: 'MJPG'
      
    # Camera calibration
    camera:
      # usbpcb camera
      intrinsics:
        fx: 344.442625
        fy: 344.225921
        cx: 331.977460
        cy: 186.828514
      distortion: [0.012006, -0.002764, 0.000038, 0.001801, 0.000000]
      fisheye: False
      undistort_crop: False