# IMPORTANT: Check v4l2-ctl --list-devices for correct ID
# exploreHD camera
/dwe_camera/exploreHD_camera_node:
  ros__parameters:
    video:
      id: 2
      width: 1280
      height: 720
      framerate: 15
      format: 'MJPG'
    compression:
      width: 320
      height: 240
      target_fps: 0
      jpeg_quality: 75
    camera:
      auto_exposure: True
      exposure_time: 156
      brightness: 0
      contrast: 32
      saturation: 64
      hue: 0
      gamma: 100
      gain: 0
      sharpness: 3
    ros:
      frame_id: "exploreHD_camera_frame" # Unique TF frame_id

# usbpcb camera
/dwe_camera/usbpcb_camera_node:
  ros__parameters:
    video:
      id: 6
      width: 1280
      height: 720
      framerate: 15
      format: 'MJPG'
    compression:
      width: 320
      height: 240
      target_fps: 0
      jpeg_quality: 75
    camera:
      auto_exposure: True
      exposure_time: 156
      brightness: 0
      contrast: 32
      saturation: 64
      hue: 0
      gamma: 100
      gain: 0
      sharpness: 3
    ros:
      frame_id: "usbpcb_camera_frame" # Unique TF frame_id